apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: tester
  namespace: etcd-e2e
spec:
  jobLabel: job
  podMetricsEndpoints:
  - port: metrics
    interval: 5s
  selector:
    matchLabels:
      app: tester
