apiVersion: v1
kind: Service
metadata:
  labels:
    name: etcd
  name: client
  namespace: etcd
spec:
  clusterIP: None
  clusterIPs:
  - None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: etcd-client
    port: 2379
    protocol: TCP
    targetPort: client
  - name: http
    port: 2378
    protocol: TCP
    targetPort: http
  - name: metrics
    port: 2381
    protocol: TCP
    targetPort: metrics
  selector:
    name: etcd
  sessionAffinity: None
  type: ClusterIP
