apiVersion: v1
kind: Service
metadata:
  name: discovery
  namespace: etcd
spec:
  clusterIP: None
  clusterIPs:
  - None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: peer
    port: 2380
    protocol: TCP
    targetPort: peer
  publishNotReadyAddresses: true
  selector:
    name: etcd
  sessionAffinity: None
  type: ClusterIP
